### ISSUE TITLE
Instead of map white screen is getting displayed.

### ISSUE THREAD

**Issue by bhumin3i** [andygup/ionic2-esri-map#11]
![screen shot 2018-05-10 at 7 22 30 pm](https://user-images.githubusercontent.com/25737987/39873223-f0370468-5487-11e8-9ce2-ceeb0f4ffb01.png)

**Comment by andygup** [comment]
@bhumin3i I have a few questions:
- Are there any console errors?
- What phone, operating system and OS version?
- What version of Ionic?
