### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by schontz** [andygup/ionic2-esri-map#17]
`.gitignore` is ignoring `*.json`.

**Comment by andygup** [comment]
Correct. As noted in the README you simply copy `index.html`, `tab1.page.html` and `tab1.page.ts` from this repo to their respective directories in your new Ionic project. You won't be able to `npm install` this repo. It didn't make sense to include an entire buildable Ionic project when there are only 3 files that need to be changed.

**Comment by schontz** [comment]
Aha. How'd I miss that?
