### ISSUE TITLE
Emulator test fails

### ISSUE THREAD

**Issue by peterennis** [andygup/ionic2-esri-map#2]
It seems to be stuck in a loop.
Deploy to device slows down development.
Is there documentation on options and best practice?
![capture040](https://cloud.githubusercontent.com/assets/140737/24297866/739d8dd4-1061-11e7-8332-8e15a9e16c5b.png)

**Comment by andygup** [comment]
@peterennis Can you provide a dump or screenshot of the Android Studio logcat messages?

Reference: https://developer.android.com/studio/debug/am-logcat.html

**Comment by peterennis** [comment]
Tested on iPad 2 with Ionic View and it worked.
I will check the Android emulator again and also an old Nexus I have, and report back.

**Comment by andygup** [comment]
Gotcha. Be sure to run the apps attached to the native debugger. That way we can capture operating system errors and application errors.
