### ISSUE TITLE
Strange behavior with zoom in

### ISSUE THREAD

**Issue by peterennis** [andygup/ionic2-esri-map#3]
This is 4th Street, Oakland.
Using Ionic lab view. Chrome.

![capture049](https://cloud.githubusercontent.com/assets/140737/24488557/65126f68-14cc-11e7-83ca-a40074bceae3.png)

![capture050](https://cloud.githubusercontent.com/assets/140737/24488560/695c5534-14cc-11e7-9cb5-9b7ede4480d1.png)

![capture051](https://cloud.githubusercontent.com/assets/140737/24488564/6e95ef56-14cc-11e7-881e-bdf5eb8cf8c9.png)

**Comment by andygup** [comment]
Thanks. Can you give me the lat/lon for that location and verify which map you are using (e.g. streets)?

**Comment by andygup** [comment]
I'm closing this out. Feel free to reopen if you still have issues.
