### ISSUE TITLE
typescript types for arcgis-js-api@3

### ISSUE THREAD

**Issue by JakobMadsen717** [andygup/ionic2-esri-map#5]
Hi Andy,

This is not an issue, just a question.

Thanks for this awesome, minimal and easy to understand prototype, makes it a breeze to get started. I would now like to get typescript typings to work, but I cannot figure out how. I think it starts like this:
`npm install --save @types/arcgis-js-api@3`

and then I have seen examples like this
```
import esri = require("esri");
import Map = require("esri/map");
import Point = require("./Point");
class MyClass {
  private myMap: Map;
  private myPoint: Point;
```

but I think my setup (VS Code) wants something more along the lines of
`import { ?? } from '@types/arcgis-js-api';`

and I simply can't figure out what to import in order to reference the types, such as Map, Point, esri.Point or whatever.

Thanks for any help, hint, pointer you can give me, and my apologies if I have asked the question in the wrong spot,
Jakob

**Comment by andygup** [comment]
Thanks @JakobMadsen717. Great question, and yes it's a little confusing how that all works. Here's a few pointers.

For the [3.x JS API types](https://github.com/tomwayson/angular-esri-loader#3x-types) you can use `import` statements. Check out this [issue](https://github.com/Esri/jsapi-resources/issues/60) for more info.

For the [4.x JS API types](https://github.com/tomwayson/angular-esri-loader#4x-types), just as an FYI, you **can** use the  `__esri` namespace for types. But for 4.x, you won't be able to `npm install` the ArcGIS API for JavaScript and then `import` modules.
