### ISSUE TITLE
Loading local api

### ISSUE THREAD

**Issue by duffcon** [andygup/ionic2-esri-map#6]
This example demonstrates using a cdn (pages/home/home.ts):

`
        this.esriLoader.load({
            url: 'https://js.arcgis.com/3.22/'
`
How would I load it locally from esri's web optimizer or custom bower build?

**Comment by andygup** [comment]
@duffcon sorry for the delay. Good question. I haven't tried it recently, but should just be able to  include a [script tag](https://github.com/Esri/esri-loader#using-your-own-script-tag) that references your local build. Be sure to place it in your `index.html` page before the script tag that loads `cordova.js`: 

```js
      <script src="scripts/esri/dojo/dojo.js" data-esri-loader="loaded"></script>
```

When you go to bootstrap the loader, I'd recommend using the CDN as a default, just in case.

Reference: https://github.com/Esri/esri-loader#using-your-own-script-tag

**Comment by andygup** [comment]
I'm going to go ahead an close this. Feel free to reopen if needed.
