### ISSUE TITLE
Geolocation fails on Ionic with no error

### ISSUE THREAD

**Issue by andygup** [andygup/ionic2-esri-map#8]
This is using default browser Geolocation API on Android 8, no location is returned:

```javascript
    navigator.geolocation.watchPosition( . . . );
    navigator.geolocation.getCurrentPosition( . . . );
```

Reproduced on Ionic version 3.18 with internet, coarse and fine perms set in manifest, and application-level `Location` permission is active/on. 

Notes: 
* This was previously verified working at Ionic v3.10 and Android 7.x.
* Geolocation works fine when you bypass WebView and use native classes on Android via a Cordova plugin: https://github.com/Esri/cordova-plugin-advanced-geolocation. 
* This could indicate an issue with WebView. Have not verified WebView version, yet.
* Not sure if this logcat message is related: `I/CarrierServices: [2] n.a: CellServiceUtils.getRegisteredCellInfo, no coarse location permission.`
* Possibly similar geolocation bug opened in 0ct 2016 on Apache JIRA [CB-12082](https://issues.apache.org/jira/browse/CB-12082?jql=status%20%3D%20Open%20AND%20text%20~%20%22webview%20geolocation%22).
* Possibly related to geolocation bug on iOS opened on Nov 3, 2017 on Apache JIRA [CB-13531](https://issues.apache.org/jira/browse/CB-13531)
* Reference: https://github.com/ionic-team/ionic-native/issues/1067

**Comment by luizvnasc** [comment]
Same error using android 6

**Comment by mora260** [comment]
Same error on iOS

**Comment by andygup** [comment]
Update: I have been able to use the `navigator.geolocation` pattern successfully using Cordova 7.0.1 by itself without Ionic. 

This implies the issue may be with the Ionic installation on WebView, because:
- Ruled out an Android SDK issue using [cordova-plugin-advanced-gelocation](https://github.com/Esri/cordova-plugin-advanced-geolocation)
- Ruled out Cordova 7.0.1 and WebView using [quickstart-map-phonegap](https://github.com/Esri/quickstart-map-phonegap)


Reference app: https://github.com/Esri/quickstart-map-phonegap

**Comment by ihadeed** [comment]
Here's a quick demo app that uses geolocation, please fork the repo and try to reproduce any issues you're having:

https://github.com/ihadeed/ionic-native-geolocation-test

```
C:\Users\Ibby\Work\geolocation-test>ionic info

cli packages: (C:\Users\Ibby\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.12.0
    npm  : 3.10.10 
    OS   : Windows 10

```

**Comment by andygup** [comment]
Looks like as of Angular 5 we need to make sure to use Ionic's `platform.ready`, example:

```javascript

  async  startLocation(){
    await this.platform.ready();
    navigator.geolocation.getCurrentPosition(function(result){ . . . }
  }

  ngOnInit(){
    . . .
    this.startLocation();
    . . . 
  }

```

**Comment by franzisk** [comment]
None of these worked for me on Android **4.1.2** and **7.0**, any other ideas? 
How about the permissions? 
Would be something on the **config.xml**?

It's working on **5.1** and **6.0**, we must find a common configuration to work on all versions. 

**Does anyone have any idea of what to try here?**

My project info:
```
% sudo ionic info                                                                                                                                                           
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.12
    Node       : v7.0.0
    npm        : 5.3.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b
```

**Comment by andygup** [comment]
>> None of these worked for me on Android 4.1.2 and 7.0, any other ideas? 

I recommend looking at the application/Ionic life cycle. Make sure to test for `navigator.geolocation`. And yes I would verify the `AndroidManifest.xml` permissions as shown here: https://github.com/andygup/ionic2-esri-map/#notes

If you are still having issues I recommend posting comments here for wider visibility: https://github.com/ionic-team/ionic-native/issues/1067

**Comment by CiroDev-Git** [comment]
Try launch with :
ionic cordova run android
Work for me. Maybe help you.
